### ISSUE TITLE
Правки лаб 3

### ISSUE THREAD

**Issue by Tulesha** [Tulesha/web-secondSemestr-Server#1]
- [x] Возвращать при создании города 201
- [x] При удалении 204
- [x] Сделать через async await
- [x] Деструктуризация объекта
- [x] Подправить отступы
- [x] Переписать обработчик ошибок по express https://expressjs.com/ru/guide/error-handling.html
- [x] Вынести key в переменную окружения
- [x] Обернуть в объект

**Comment by Tulesha** [comment]
@BakasaRus можете пожалуйста чекнуть, вроде все исправил.
Обработка ошибок реализована через [express-async-handler](https://www.npmjs.com/package/express-async-handler).
И обернуть в объект в это в fetch.js по коммиту посмотреть можно.
Остальные таски вроде как понятны)))

**Comment by BakasaRus** [comment]
А не было разговора про то, чтобы сделать подключение маршрутов вот по этому гайду?
https://expressjs.com/ru/guide/routing.html

Вроде бы я всем, у кого разделены маршруты, это показываю

**Comment by Tulesha** [comment]
@BakasaRus сделал нормальное подключение, последним коммитом

**Comment by BakasaRus** [comment]
Да, вижу. Теперь ещё [вот тут](https://github.com/Tulesha/web-secondSemestr-Server/blob/e774613f64/index.js#L16) переделать на async/await, и можно радоваться жизни

**Comment by Tulesha** [comment]
[Сделано ](https://github.com/Tulesha/web-secondSemestr-Server/blob/76f12fa95ed9b9e3e7587b03b7a7addce761bf4e/index.js)

**Comment by BakasaRus** [comment]
Вижу, можно закрывать
